[project]
name = "jacob-ladder"
version = "0.1.0"
description = "Jacob Latter Python Workspace"
readme = "README.md"
requires-python = ">=3.10, <3.11"
dependencies = [
    "cuvslam",
    "depthai>=2.22.0.0",
    "numpy>=1.24,<2",
    "rerun-sdk",
    "ruff",
    "scipy",
    "ty",
]

[project.optional-dependencies]
yolo = [
    "opencv-python==4.9.0.80",
    "ultralytics",
]

[tool.uv.sources]
cuvslam = { url = "https://github.com/nvidia-isaac/cuVSLAM/releases/download/v16.0.0/cuvslam-16.0.0+cu12-cp310-cp310-manylinux_2_35_aarch64.whl" }
